### ISSUE TITLE
Is this thing alive?

### ISSUE THREAD

**Issue by XenGi** [c-base/c-beam-ios#1]

**Comment by mmoyle** [comment]
Hi XenGi, 

The purpose of this repo is to build an ios version of c-beam. I think it would be a great way to learn ios as it is not a huge project, and has some clearly defined interesting features. I have gotten busy and distracted but this project is still on my mind. Are you interested in working on this as well? If so it would be great to team up. 

cheers,
Michael / Xeraphin

**Comment by XenGi** [comment]
Hi xeraphin,

Nice to hear that this project isn't dead. Sadly I'm not involved in the iWorld but maybe you can find some helpful hands in our irc channel or on the mailing list.
