### ISSUE TITLE
poke

### ISSUE THREAD

**Issue by XenGi** [c-base/c-beam-ios#2]
Is this project still alive?
How do ios users access c-beam from outside c-base atm? XMPP? IRC? Webapp?

**Comment by cmile** [comment]
we made some efforts to make at least the web interface usable with fruit-device:

https://c-beam.cbrp3.c-base.org

**Comment by XenGi** [comment]
But it's not accessible from outside c-base.

**Comment by cmile** [comment]
yeah, just like most c-beam functionalities only work when you're on board of c-base

**Comment by XenGi** [comment]
But it would be nice for iOS users to set their ETA with a iOS alternative to the app. Not everybody is on IRC or uses XMPP.
My answer to this issue is usually to use the mentioned systems but there are members who would like an app or a web site.

**Comment by berlincount** [comment]
I think the best way to solves this would be getting a working VPN (alternative) for iOS.

**Comment by XenGi** [comment]
I think the problem is that iOS only supports TAP devices and our VPN config is using a TUN device. Is this interchangeable? I tried to tinker with the config on m00ds iPhone a few weeks ago, but didn't succeed. Is there no official OpenVPN capable App for iOS?
VPN aside a simple website for ETA like the Android App would be totally ok.
Or one of the many iOS users we have on board code an app. Isn't there a cool new programming language to learn?

**Comment by starpeak** [comment]
https://itunes.apple.com/de/app/openvpn-connect/id590379981?mt=8 - but I did not test it yet with the c-base VPN
